CREATE TABLE inserate(
        inserat_id INTEGER PRIMARY KEY,
        source VARCHAR(255)  REFERENCES sources(name),
        viertel INTEGER REFERENCES viertel(plz),
        titel VARCHAR(255),
        groesse INTEGER,
        miete_gesamt INTEGER,
        miete_kalt INTEGER,
        miete_sonstige INTEGER,
        nebenkosten INTEGER,
        kaution INTEGER,
        abstandszahlung INTEGER,
        zimmer INTEGER,
        verfuegbarkeit DATE,
        adresse VARCHAR(255),
        url VARCHAR(255),
        kontakt VARCHAR(255),
        verfuegbar BOOLEAN,
        insert_date DATE NOT NULL DEFAULT CURRENT_DATE 
);
